// <auto-generated />
using System.Collections.Generic;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<List<string>>("LegalEntities")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Api.Entities.Contract", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ContractCurrency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("ContractDate")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("FactualBalance")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LegalEntity")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("contracts", (string)null);
                });

            modelBuilder.Entity("Api.Entities.Request", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("LegalEntity")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LogisticsType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Nomenclature")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RequestContract")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RequestDate")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("RequestStatus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("requests", (string)null);
                });

            modelBuilder.Entity("Api.Entities.ShipmentLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Nomenclature")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Quantity")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Shipped")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Warehouse")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("shipment_lines", (string)null);
                });

            modelBuilder.Entity("Api.Entities.Request", b =>
                {
                    b.OwnsOne("Api.Entities.PowerOfAttorneyData", "PowerOfAttorney", b1 =>
                        {
                            b1.Property<string>("RequestId")
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("BorderCrossing")
                                .HasColumnType("text");

                            b1.Property<string>("CarrierId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CarrierName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("DeliveryAddress")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("DriverFullName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("DriverPhoneNumber")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("RequestId");

                            b1.ToTable("requests");

                            b1.ToJson("PowerOfAttorney");

                            b1.WithOwner()
                                .HasForeignKey("RequestId");

                            b1.OwnsOne("Api.Entities.PowerOfAttorneyAttachmentData", "Attachment", b2 =>
                                {
                                    b2.Property<string>("PowerOfAttorneyDataRequestId")
                                        .HasColumnType("character varying(64)");

                                    b2.Property<string>("ContentBase64")
                                        .HasColumnType("text");

                                    b2.Property<string>("ContentType")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("FileName")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<long>("FileSize")
                                        .HasColumnType("bigint");

                                    b2.HasKey("PowerOfAttorneyDataRequestId");

                                    b2.ToTable("requests");

                                    b2.WithOwner()
                                        .HasForeignKey("PowerOfAttorneyDataRequestId");
                                });

                            b1.Navigation("Attachment");
                        });

                    b.OwnsOne("Api.Entities.VehicleInfoData", "VehicleInfo", b1 =>
                        {
                            b1.Property<string>("RequestId")
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("CarBrandAndModel")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CarPlateNumber")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("TractorId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("TrailerBrandAndModel")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("TrailerId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("TrailerPlateNumber")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("RequestId");

                            b1.ToTable("requests");

                            b1.ToJson("VehicleInfo");

                            b1.WithOwner()
                                .HasForeignKey("RequestId");
                        });

                    b.Navigation("PowerOfAttorney");

                    b.Navigation("VehicleInfo");
                });

            modelBuilder.Entity("Api.Entities.ShipmentLine", b =>
                {
                    b.HasOne("Api.Entities.Request", "Request")
                        .WithMany("ShipmentLines")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Api.Entities.Request", b =>
                {
                    b.Navigation("ShipmentLines");
                });
#pragma warning restore 612, 618
        }
    }
}
